### ISSUE TITLE
Strings are saved with quotes

### ISSUE THREAD

**Issue by silmaril42** [Kieran-Lock/SQLiteFrame#3]
When writing data to string field, the string in the SQLite DB contains not only the string value, but also a pair of double quotes.

It looks like the SQL INSERT or UPDATE statement contains `'"MyString"'` instead of `'MyString'` for the values.

**Comment by Kieran-Lock** [comment]
Thanks for the feedback @silmaril42.
I am on holiday at the moment so will not be able to address these issues, as I don't have access to a suitable editor, but will investigate and roll out a fix in due course - hopefully within the next month.

For this, it might just be a fix in `sqliteframe/types/string.py`, in the `encode` method (getting rid of the quotes around the result). I'm not exactly sure, but that is a possible cause.

**Comment by Kieran-Lock** [comment]
@silmaril42 
I have rolled out a fix for this issue, but it is currently only accessible via the dev branch on this repository. If you can, let me know if this fixes your issue. I will merge and publish as soon as possible, but it won't be for a while. Thanks!

**Comment by Kieran-Lock** [comment]
Fixed this bug in the latest release - 0.3.1.
