### ISSUE TITLE
Table creation does not preserve order of fields

### ISSUE THREAD

**Issue by silmaril42** [Kieran-Lock/SQLiteFrame#4]
When creating a table, the fields are generated in alphabetical order. The order from the class in the python code is not preserved.

## Example
This class from the project example
```py
@table(database)
class TableName:
    primary_key_field = String(primary_key=True)  # The primary key parameter is False by default
    second_column = Integer  # If only the default options are required, no brackets are necessary either
    third_column = Boolean(nullable=True)  # The nullable parameter is False by default
    fourth_column = String(default="This is a default value.")  # You can also opt-in to giving columns default values like this
```

leads to this debug output:
```
CREATE TABLE IF NOT EXISTS TableName (
	fourth_column TEXT NOT NULL DEFAULT "This is a default value.",
	primary_key_field TEXT PRIMARY KEY NOT NULL,
	second_column INTEGER NOT NULL,
	third_column BOOLEAN
);
```

`fourth_column ` should be the last item in the `CREATE TABLE` statement, but it's the first, because the fields have been sorted alphabetically.

**Comment by Kieran-Lock** [comment]
@silmaril42 thanks for raising an issue.
This seems to be as a result of the internal `inspect.getmembers` call returning declared columns in alphabetical order within `sqliteframe/entity/entity.py`, in the `extract_columns method`. I will have to investigate this further and see if there's a way to return them in the order of declaration or a similar solution. I will roll out a fix as soon as possible, but do not have access to an editor at the moment.

A genuine question - why is it important to preserve this order? When I was making the library initially I did not realise this to be an issue. I started the project just to deal with some simple SQL problems and to see if I could build these queries with a nice API, so I'm by no means an SQL expert. Please let me know. Thanks!

**Comment by silmaril42** [comment]
Thank you @Kieran-Lock!

Your library looks like the perfect size of a tool to wrap simple SQLite DBs that are used as data containers for small web apps that don't warrant a "real" database.

For my current project I just coded it manually, because the string quotation issue #3 is a show stopper for me.
But this application only needs one small table, so it's no big deal anyway.

I am optimistic, that this kind of "minimal ORM" is something that might help a lot in building clean structured code instead of a wild mess of SQL statements 😄

**Comment by Kieran-Lock** [comment]
@silmaril42 
I've been working on this and have introduced the functionality as an opt-in feature to preserve the order of columns. This is because the best way I could find was to record and store the fields of the defined class in the schema with metaclasses - to keep the API the same this feature must therefore be opt-in with this current fix.

Just make your table declaration inherit from `PreserveOrder`, which implements the metaclass for you. See `schema.py` in the repo for an example.
